logging:
  level:
    root: INFO
    org.springframework: INFO
    pe.realplaza.budgets: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.simple.SimpleJdbcCall: INFO
    org.springframework.web.client.RestTemplate: INFO
spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bellatrix?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    initialization-mode: never
  jackson:
    time-zone: America/Lima
    date-format: yyyy-MM-dd HH:mm:ss
    locale: es_PE
    default-property-inclusion: non_null


